### ISSUE TITLE
Add branch protection on "master"

### ISSUE THREAD

**Issue by axel3rd** [peio42/cerberus#10]
Pushing directly on *master* is really a bad practice. SonarCloud Quality Gates can be failed in this case (sample on [last commit](https://sonarcloud.io/dashboard?id=org.blutch%3Acerberus)).

In [Branch protection rules](https://github.com/peio42/cerberus/settings/branches) add new rule on `master` with : 
- *Require status checks to pass before merging*
- *Require branches to be up to date before merging*
- Check *SonarCloud Code Analysis*
- Check *continuous-integration/travis-ci*
- *Include administrators* ;)

Only repository owner can do that.

**Comment by peio42** [comment]
Done, but I couldn't check "SonarCloud Analysis"...
Only "continuous-integration/travis-ci" was available.
Normal?

**Comment by axel3rd** [comment]
> Done, but I couldn't check "SonarCloud Analysis"...

The checks appears after some run => perhaps more PR with SonarCloud analysis are required before check available
