### ISSUE TITLE
Invalid travis coverage

### ISSUE THREAD

**Issue by peio42** [peio42/cerberus#11]
Last coverage is low, mainly because file "tests/go.js" has all its 229 lines of code uncovered.
This value is necessarily wrong, has it is the main script for "npm test" (and should be close to 100%)...

**Comment by axel3rd** [comment]
@peio42 : unit tests is part of *project sources* => they can't instrument itself for code coverage. The best solution is to exclude them of code coverage.

**Comment by peio42** [comment]
So let's move "lib/test.js" into "test" folder (renaming as "test/helper.js" or so) and exclude "test/*" folder from code coverage... ?
